/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 plain_piano.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { useCustomization } from '../src/context/Customization'

const Piano = (props) => {

  const { material } = useCustomization();
  const { nodes, materials } = useGLTF('public/plain_piano.gltf')

  const orangeBodyColor = useTexture({
    map: 'public/colors/orangecolor.jpeg'
  })
  const redBodyColor = useTexture({
    map: 'public/colors/redcolor.png'
  })
  const whiteBodyColor = useTexture({
    map: 'public/colors/whitecolor.png'
  })
  const blackBodyColor = useTexture({
    map: 'public/colors/blackcolor.jpeg'
  })
  const greyBodyColor = useTexture({
    map: 'public/colors/greycolor.png'
  })

  const orangeBaseColor = useTexture({
    map: 'public/colors/orangecolor.jpeg'
  })
  const redBaseColor = useTexture({
    map: 'public/colors/redcolor.png'
  })
  const whiteBaseColor = useTexture({
    map: 'public/colors/whitecolor.png'
  })
  const blackBaseColor = useTexture({
    map: 'public/colors/blackcolor.jpeg'
  })
  const greyBaseColor = useTexture({
    map: 'public/colors/greycolor.png'
  })


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Body1.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body10.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body101.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body102.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body103.geometry} material={materials['Opaque(165,158,150)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body11.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body111.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body112.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body12.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body121.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body122.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body13.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body131.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body132.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body14.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body141.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body142.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body15.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body151.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body152.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body16.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body161.geometry} material={materials['Opaque(230,181,112)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body162.geometry} material={materials['Opaque(230,181,112)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body17.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body171.geometry} material={materials['Opaque(64,64,64)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body172.geometry} material={materials['Opaque(64,64,64)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body18.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body19.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body11_1.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body110.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body111_1.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body112_1.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body113.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body114.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body115.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body116.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body117.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body118.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body119.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body12_1.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body120.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body121_1.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body122_1.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body123.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body124.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body125.geometry} material={nodes.Body125.material} rotation={[0, 0, 0]} />

      <mesh geometry={nodes.Body126.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body127.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />

      <mesh geometry={nodes.Body128.geometry} material={nodes.Body128.material} rotation={[0, 0, 0]} />
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body129_1.geometry} material={materials['Opaque(23,57,107)']} />
        <mesh geometry={nodes.Body129_2.geometry} material={materials['Opaque(255,255,242)']} />
        <mesh geometry={nodes.Body129_3.geometry} material={materials['Opaque(255,255,0)']} />
      </group>
      <mesh geometry={nodes.Body13_1.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body130.geometry} material={materials['Opaque(128,128,128)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body131_1.geometry} material={materials['Opaque(128,128,128)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body132_1.geometry} material={materials['Opaque(128,128,128)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body133.geometry} material={materials['Opaque(128,128,128)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body134.geometry} material={materials['Opaque(128,128,128)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body135.geometry} material={materials['Opaque(128,128,128)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body136.geometry} material={materials['Opaque(128,128,128)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body137.geometry} material={materials['Opaque(128,128,128)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body138.geometry} material={materials['Opaque(41,210,224)']} rotation={[0, 0, 0]} />
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body139_1.geometry} material={materials['Opaque(63,63,63)']} />
        <mesh geometry={nodes.Body139_2.geometry} material={materials['Opaque(255,255,255)']} />
        <mesh geometry={nodes.Body139_3.geometry} material={materials['Opaque(192,192,192)']} />
      </group>
      <mesh geometry={nodes.Body14_1.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body140.geometry} material={materials['Opaque(160,160,160)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body141_1.geometry} material={materials['Opaque(219,210,199)']} rotation={[0, 0, 0]} />
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body142_3.geometry} material={materials['Opaque(64,64,64)']} />
        <mesh geometry={nodes.Body142_4.geometry} material={materials['Opaque(162,175,191)']} />
        <mesh geometry={nodes.Body142_5.geometry} material={materials['Steel_-_Satin']} />
      </group>
      <mesh geometry={nodes.Body143.geometry} material={materials['Steel_-_Satin']} rotation={[0, 0, 0]} />
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body144_1.geometry} material={materials['Opaque(0,192,0)']} />
        <mesh geometry={nodes.Body144_2.geometry} material={materials['Opaque(255,255,128)']} />
      </group>
      <mesh geometry={nodes.Body145.geometry} material={materials['Opaque(165,158,150)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body146.geometry} material={materials['Opaque(64,64,64)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body147.geometry} material={materials['Opaque(64,64,64)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body148.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body149.geometry} material={materials['Opaque(165,158,150)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body15_1.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body150.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body151_3.geometry} material={materials['Opaque(170,178,196)']} />
        <mesh geometry={nodes.Body151_4.geometry} material={materials['Opaque(255,255,0)']} />
        <mesh geometry={nodes.Body151_5.geometry} material={materials['Opaque(0,192,0)']} />
        <mesh geometry={nodes.Body151_6.geometry} material={materials['Opaque(128,128,128)']} />
        <mesh geometry={nodes.Body151_7.geometry} material={materials['Opaque(247,224,153)']} />
      </group>
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body152_3.geometry} material={materials['Opaque(229,229,229)']} />
        <mesh geometry={nodes.Body152_4.geometry} material={materials['Opaque(247,224,153)']} />
      </group>
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body153_1.geometry} material={materials['Opaque(229,229,229)']} />
        <mesh geometry={nodes.Body153_2.geometry} material={materials['Opaque(247,224,153)']} />
      </group>
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body154_1.geometry} material={materials['Opaque(229,229,229)']} />
        <mesh geometry={nodes.Body154_2.geometry} material={materials['Opaque(247,224,153)']} />
      </group>
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body155_1.geometry} material={materials['Opaque(170,178,196)']} />
        <mesh geometry={nodes.Body155_2.geometry} material={materials['Opaque(2,60,210)']} />
        <mesh geometry={nodes.Body155_3.geometry} material={materials['Opaque(247,224,153)']} />
      </group>
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body156_1.geometry} material={materials['Opaque(128,128,128)']} />
        <mesh geometry={nodes.Body156_2.geometry} material={materials['Opaque(255,255,255)']} />
      </group>
      <mesh geometry={nodes.Body157.geometry} material={materials['Opaque(229,229,229)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body158.geometry} material={materials['Opaque(165,158,150)']} rotation={[0, 0, 0]} />
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body159_1.geometry} material={materials['Opaque(128,128,128)']} />
        <mesh geometry={nodes.Body159_2.geometry} material={materials['Opaque(255,255,255)']} />
        <mesh geometry={nodes.Body159_3.geometry} material={materials['Opaque(170,178,196)']} />
      </group>
      <mesh geometry={nodes.Body16_1.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body160_1.geometry} material={materials['Opaque(170,178,196)']} />
        <mesh geometry={nodes.Body160_2.geometry} material={materials['Opaque(128,128,128)']} />
        <mesh geometry={nodes.Body160_3.geometry} material={materials['Opaque(247,224,153)']} />
      </group>
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body161_3.geometry} material={materials['Opaque(128,128,128)']} />
        <mesh geometry={nodes.Body161_4.geometry} material={materials['Opaque(170,178,196)']} />
        <mesh geometry={nodes.Body161_5.geometry} material={materials['Opaque(255,255,255)']} />
      </group>
      <group rotation={[0, 0, 0]}>
        <mesh geometry={nodes.Body162_3.geometry} material={materials['Opaque(128,128,128)']} />
        <mesh geometry={nodes.Body162_4.geometry} material={materials['Opaque(170,178,196)']} />
        <mesh geometry={nodes.Body162_5.geometry} material={materials['Opaque(255,255,255)']} />
      </group>
      <mesh geometry={nodes.Body163.geometry} material={materials['ABS_(White)_1']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body164.geometry} material={materials['ABS_(White)_1']} rotation={[0, 0, 0]} />

      

      <mesh geometry={nodes.Body165.geometry} rotation={[0, 0, 0]}>
        <meshStandardMaterial
          metalness={0.5}
          roughness={0.5}
          {...(material === "orange"
            ? orangeBodyColor
            : material === "white"
              ? whiteBodyColor
              : material === "whiteblack"
                ? whiteBodyColor
                : material === "grey"
                ? greyBodyColor
                : material === "red"
                ? redBodyColor
                  : pass)
                }
        />
      </mesh>

      <mesh geometry={nodes.Body17_1.geometry} material={materials['ABS_(White)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body18_1.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body19_1.geometry} material={materials['ABS_(White)_(1)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body2.geometry} material={materials['Steel_-_Satin']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body20.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body21.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body22.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body23.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body24.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body25.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body26.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />



      <mesh geometry={nodes.Body27.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body28.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body29.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body21_1.geometry} material={materials['Opaque(165,158,150)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body22_1.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body23_1.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body24_1.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body25_1.geometry} material={materials['Opaque(192,192,192)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body26_1.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body27_1.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body3.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body30.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body31.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body32.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body33.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body34.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body35.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body36.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body37.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body38.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body39.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body31_1.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body32_1.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body33_1.geometry} material={materials['Opaque(192,192,192)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body34_1.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body35_1.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body4.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body40.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body41.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body41_1.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body42.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body43.geometry} material={materials['Opaque(26,26,26)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body44.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body45.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body5.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body51.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body52.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body53.geometry} material={materials['Opaque(192,192,192)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body54.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body55.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body6.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body61.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body62.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body63.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body7.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body71.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body72.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body73.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body8.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body81.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body82.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body83.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body9.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body91.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body92.geometry} material={materials['Opaque(165,131,0)']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Body93.geometry} material={materials['Opaque(165,132,0)']} rotation={[0, 0, 0]} />


      <mesh geometry={nodes.Cabinet_Cap.geometry} rotation={[0, 0, 0]}>
        <meshStandardMaterial
          metalness={0.5}
          roughness={0.5}
          {...(material === "orange"
            ? blackBaseColor
            : material === "white"
              ? whiteBaseColor
              : material === "whiteblack"
                ? blackBaseColor
                : material === "grey"
                ? greyBaseColor
                : material === "red"
                ? blackBaseColor
                  : pass)}
        />
      </mesh>

    </group>
  )
}

useGLTF.preload('/plain_piano.gltf')

export default Piano;
